name = "ProjectAssigner"
uuid = "40c276f3-910b-46f6-a8e5-80a1b18107b2"
authors = ["Zachary Sunberg <zachary.sunberg@colorado.edu> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "1"
CSV = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
